name: Build addon for firefox

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events to matching any tag format, i.e. 1.0, 20.15.10
jobs:
  build-chromium:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x" # You might need to adjust this value to your own version
      - name: Build
        id: build
        run: |
          sudo apt install jq --yes
          cat <<< $(jq 'del(.browser_specific_settings)' manifest.json) > manifest.json
          cat <<< $(jq 'del(.applications)' manifest.json) > manifest.json
          npm install -g yarn
          yarn
          yarn run build
          yarn run package
          ls
          echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"
          mv distribution/favicon_for_links.zip distribution/favicon_for_links_chromium.zip
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.ref }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./distribution/*.zip"]'
